<?php

echo "<title>Home page</title>";

echo "<h1>Hello!</h1>";

echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary']);

echo "<br>";
echo "<br>";
echo "<br>";

if (count($users) > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo count($users); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <?php $user = explode('=', $user); ?>
            <tr>
                <td><?php echo $user[0]; ?></td>
                <td><?php echo $user[1]; ?></td>
                <td><?php echo $user[2]; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}